### ISSUE TITLE
How to solve the problem that topK's K is different for every input text?

### ISSUE THREAD

**Issue by guotong1988** [AlexGidiotis/Document-Classifier-LSTM#11]
The output topK's K is fixed now.

Do you think training a classifier to predict the value of K for every input is a good solution?

Thank you very much.

**Comment by AlexGidiotis** [comment]
Hi @guotong1988. Actually, this is an option I have explored a bit in the past and failed to make it work. In theory, it should be possible to train your model to predict the K value as well.
