### ISSUE TITLE
Redefining f1 score

### ISSUE THREAD

**Issue by shuttle1987** [AlexGidiotis/Document-Classifier-LSTM#13]
I notice that `f1_score` is imported here:

https://github.com/AlexGidiotis/Document-Classifier-LSTM/blob/6220e70ec31135c9795a46d0f17f2bb6b5fee8b0/hatt_classifier.py#L29

But then redefined here:

https://github.com/AlexGidiotis/Document-Classifier-LSTM/blob/6220e70ec31135c9795a46d0f17f2bb6b5fee8b0/hatt_classifier.py#L53

Can the import or the function definition be removed here?

**Comment by AlexGidiotis** [comment]
Hi @shuttle1987 Actually, in recent TF versions, F1 score is implemented in the tensorflow-addons library and can be readily used.
