### ISSUE TITLE
Regarding better accuracy with BILSTM Attention

### ISSUE THREAD

**Issue by spartian** [AlexGidiotis/Document-Classifier-LSTM#3]
You mentioned in your readme file that you achieved better accuracy with BILSTM attention instead of HAN. **What did you mean by BILSTM attention?** I want to know the architecture. Are you referring to any specific research paper? How is the architecture different from HAN?

**Comment by AlexGidiotis** [comment]
The architecture is in the classifier.py file. It is a simple blstm layer with attention on top. There might be a number of reasons why HAN does not perform as well. I suspect the more complex architecture might be overfitting slightly.

**Comment by spartian** [comment]
Thank you for the answer...I will look into classifier.py file.
